# Generated by Django 2.2.13 on 2020-06-13 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=50)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('is_spam', models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default='False')),
            ],
        ),
        migrations.CreateModel(
            name='Contact_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.TextField(max_length=30)),
                ('phone_number', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User_info')),
            ],
        ),
    ]
