# Generated by Django 2.2.13 on 2020-06-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200613_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='is_spam',
        ),
        migrations.AddField(
            model_name='contact_info',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
