# Generated by Django 2.2.13 on 2020-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200613_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='is_spam',
            field=models.BooleanField(choices=[('TRUE', 'True'), ('FALSE', 'False')], default=True),
        ),
    ]
